# Generated by Django 3.0.3 on 2021-10-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_parent', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(max_length=100)),
                ('vat_reg_no', models.TextField(max_length=100)),
                ('cr_no', models.TextField(max_length=100)),
                ('expired_on', models.TextField(max_length=100)),
                ('land_phone', models.TextField(max_length=100)),
                ('mobile', models.TextField(max_length=100)),
                ('contact_person', models.TextField(max_length=100)),
                ('contact_mobile', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('open_balance', models.TextField(max_length=100)),
                ('credit_lim_am', models.TextField(max_length=100)),
                ('credit_lim_dur', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.TextField(max_length=100)),
                ('nationality', models.TextField(max_length=100)),
                ('birth_date', models.TextField(max_length=100)),
                ('joining_date', models.TextField(max_length=100)),
                ('designation', models.TextField(max_length=100)),
                ('department', models.TextField(max_length=100)),
                ('salary_categ', models.TextField(max_length=100)),
                ('passport_no', models.TextField(max_length=100)),
                ('expir', models.TextField(max_length=100)),
                ('id_no', models.TextField(max_length=100)),
                ('id_expir', models.TextField(max_length=100)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('basic', models.TextField(max_length=100)),
                ('housing', models.TextField(max_length=100)),
                ('transportation', models.TextField(max_length=100)),
                ('food', models.TextField(max_length=100)),
                ('mobile', models.TextField(max_length=100)),
                ('other', models.TextField(max_length=100)),
                ('netpay', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_parent', models.TextField(max_length=100)),
                ('expenses_child', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(max_length=100)),
                ('category', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_parent', models.TextField(max_length=100)),
                ('income_child', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.TextField(max_length=100)),
                ('item_desc', models.TextField(max_length=500, null=True)),
                ('item_barcode', models.TextField(max_length=50)),
                ('item_category', models.TextField(max_length=50)),
                ('item_unit_prim', models.TextField(max_length=100)),
                ('item_unit_sec', models.TextField(max_length=100)),
                ('open_balance', models.TextField(max_length=100)),
                ('buying_price', models.TextField(max_length=50)),
                ('sell_price', models.TextField(max_length=50)),
                ('image1', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('image2', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('image3', models.ImageField(null=True, upload_to='images/', verbose_name='')),
                ('image4', models.ImageField(null=True, upload_to='images/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField(max_length=100)),
                ('job_desc', models.TextField(max_length=500, null=True)),
                ('imag1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imag2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imag3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imag4', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledger_name', models.TextField(max_length=100)),
                ('group_name', models.TextField(max_length=100)),
                ('category', models.TextField(max_length=100)),
                ('opening_bal', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_parent', models.TextField(max_length=100)),
                ('liability_child', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(max_length=100)),
                ('vat_reg_no', models.TextField(max_length=100)),
                ('cr_no', models.TextField(max_length=100)),
                ('expired_on', models.TextField(max_length=100)),
                ('land_phone', models.TextField(max_length=100)),
                ('mobile', models.TextField(max_length=100)),
                ('contact_person', models.TextField(max_length=100)),
                ('contact_mobile', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('open_balance', models.TextField(max_length=100)),
                ('credit_lim_am', models.TextField(max_length=100)),
                ('credit_lim_dur', models.TextField(max_length=100)),
                ('bank_acc_name', models.TextField(max_length=100)),
                ('bank_acc_no', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.TextField(max_length=100)),
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
