# Generated by Django 3.2.7 on 2021-09-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(max_length=100)),
                ('vat_reg_no', models.TextField(max_length=100)),
                ('cr_no', models.TextField(max_length=100)),
                ('expired_on', models.TextField(max_length=100)),
                ('land_phone', models.TextField(max_length=100)),
                ('mobile', models.TextField(max_length=100)),
                ('contact_person', models.TextField(max_length=100)),
                ('contact_mobile', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('open_balance', models.TextField(max_length=100)),
                ('credit_lim_am', models.TextField(max_length=100)),
                ('credit_lim_dur', models.TextField(max_length=100)),
            ],
        ),
    ]
