# Generated by Django 3.0.3 on 2021-10-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0002_delete_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_parent', models.TextField(max_length=100)),
                ('asset_child', models.TextField(max_length=100)),
                ('new_child', models.TextField(max_length=100)),
                ('child', models.TextField(max_length=100)),
            ],
        ),
    ]
