# Generated by Django 3.1.12 on 2021-11-02 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0002_group_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='parent',
            new_name='ledger_id',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='parent',
            new_name='ledger_id',
        ),
    ]
