# Generated by Django 3.0.3 on 2021-10-13 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0003_asset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Expences',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Liabilities',
        ),
    ]
