# Generated by Django 3.1.12 on 2021-11-02 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0003_auto_20211102_0743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='ledger_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='ledger',
            old_name='ledger_id',
            new_name='group',
        ),
    ]
