# Generated by Django 3.0.3 on 2021-10-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0004_auto_20211013_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_parent', models.TextField(max_length=100)),
                ('expenses_child', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_parent', models.TextField(max_length=100)),
                ('income_child', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_parent', models.TextField(max_length=100)),
                ('liability_child', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_child', models.TextField(max_length=100)),
                ('asset_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Sam.Asset')),
            ],
            options={
                'verbose_name_plural': 'Assets',
                'ordering': ('asset_child',),
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
            ],
            options={
                'verbose_name_plural': 'categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Sam.asset',),
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
            ],
            options={
                'verbose_name_plural': 'subcategories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Sam.category',),
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sam.subcategory')),
            ],
        ),
    ]
