# Generated by Django 3.0.3 on 2021-10-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0005_asset_category_expences_income_liabilities_product_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
