# Generated by Django 3.1.12 on 2021-11-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0005_auto_20211102_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger_Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(max_length=100)),
                ('ledger_name', models.TextField(max_length=100)),
                ('ledger_id', models.TextField(max_length=100)),
                ('period', models.TextField(max_length=100)),
                ('ledger_category', models.TextField(max_length=100)),
                ('openingbalance', models.IntegerField(max_length=100)),
                ('credit_amount', models.TextField(max_length=100)),
                ('debit_amount', models.TextField(max_length=100)),
                ('Balance', models.TextField(max_length=100)),
            ],
        ),
    ]
