# Generated by Django 3.2.7 on 2021-09-16 09:16

import Sam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0005_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.TextField(max_length=100)),
                ('job_desc', models.TextField(max_length=500, null=True)),
                ('imag1', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
                ('imag2', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
                ('imag3', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
                ('imag4', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
            ],
        ),
    ]
