# Generated by Django 3.1.12 on 2021-11-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0006_ledger_statement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger_statement',
            old_name='ledger_name',
            new_name='general_ledger',
        ),
    ]
