# Generated by Django 3.2.7 on 2021-09-16 09:24

import Sam.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0006_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.TextField(max_length=100)),
                ('nationality', models.TextField(max_length=100)),
                ('birth_date', models.TextField(max_length=100)),
                ('joining_date', models.TextField(max_length=100)),
                ('designation', models.TextField(max_length=100)),
                ('department', models.TextField(max_length=100)),
                ('salary_categ', models.TextField(max_length=100)),
                ('passport_no', models.TextField(max_length=100)),
                ('expir', models.TextField(max_length=100)),
                ('id_no', models.TextField(max_length=100)),
                ('id_expir', models.TextField(max_length=100)),
                ('img1', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
                ('img2', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
                ('img3', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
                ('img4', models.ImageField(blank=True, null=True, upload_to=Sam.models.filepath)),
                ('basic', models.TextField(max_length=100)),
                ('housing', models.TextField(max_length=100)),
                ('transportation', models.TextField(max_length=100)),
                ('food', models.TextField(max_length=100)),
                ('mobile', models.TextField(max_length=100)),
                ('other', models.TextField(max_length=100)),
                ('netpay', models.TextField(max_length=100)),
            ],
        ),
    ]
