# Generated by Django 3.2.7 on 2021-09-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.TextField(max_length=100)),
                ('category', models.TextField(max_length=100)),
            ],
        ),
    ]
