# Generated by Django 3.0.3 on 2021-10-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0007_category_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='id_parent',
            new_name='id_child',
        ),
    ]
