# Generated by Django 3.0.3 on 2021-10-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0008_auto_20211013_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='id_child',
        ),
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('price', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('id_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sam.SubCategory')),
            ],
        ),
    ]
