# Generated by Django 3.2.3 on 2021-09-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0010_auto_20210929_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='image4',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
