# Generated by Django 3.2.3 on 2021-10-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0011_auto_20210930_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_parent', models.TextField(max_length=100)),
                ('asset_child', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenses_parent', models.TextField(max_length=100)),
                ('expenses_child', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_parent', models.TextField(max_length=100)),
                ('income_child', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liability_parent', models.TextField(max_length=100)),
                ('liability_child', models.TextField(max_length=100)),
            ],
        ),
    ]
