# Generated by Django 3.2.7 on 2021-10-14 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0011_alter_asset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sam.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(default='dynamic', max_length=15),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sam.asset'),
        ),
    ]
