# Generated by Django 3.2.3 on 2021-10-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0012_asset_expences_income_liabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_invoice', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
                ('invoice_no', models.TextField(max_length=100)),
                ('cusomer_id', models.TextField(max_length=100)),
                ('customer_name', models.TextField(max_length=100)),
                ('si_no1', models.TextField(max_length=100)),
                ('si_no2', models.TextField(max_length=100)),
                ('date1', models.TextField(max_length=100)),
                ('date2', models.TextField(max_length=100)),
                ('ref_no1', models.TextField(max_length=100)),
                ('ref_no2', models.TextField(max_length=100)),
                ('description1', models.TextField(max_length=100)),
                ('description2', models.TextField(max_length=100)),
                ('item1', models.TextField(max_length=100)),
                ('item2', models.TextField(max_length=100)),
                ('qty1', models.TextField(max_length=100)),
                ('qty2', models.TextField(max_length=100)),
                ('job1', models.TextField(max_length=100)),
                ('job2', models.TextField(max_length=100)),
                ('sales_staff1', models.TextField(max_length=100)),
                ('sales_staff2', models.TextField(max_length=100)),
                ('amount', models.TextField(max_length=100)),
                ('balance_amount', models.TextField(max_length=100)),
            ],
        ),
    ]
