# Generated by Django 3.2.7 on 2021-10-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0013_customerinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.TextField(max_length=100)),
                ('supplier_name', models.TextField(max_length=100)),
                ('report_date', models.TextField(max_length=100)),
                ('invoice_no', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='customer_invoice',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='date1',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='date2',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='job1',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='job2',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='qty1',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='qty2',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='ref_no1',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='ref_no2',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='sales_staff1',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='sales_staff2',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='si_no1',
        ),
        migrations.RemoveField(
            model_name='customerinvoice',
            name='si_no2',
        ),
    ]
