# Generated by Django 3.0.3 on 2021-10-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0013_auto_20211013_1049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
