# Generated by Django 3.2.7 on 2021-10-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0014_auto_20211021_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.TextField(max_length=100)),
                ('item_name', models.TextField(max_length=100)),
                ('date', models.TextField(max_length=100)),
                ('period', models.TextField(max_length=100)),
            ],
        ),
    ]
