# Generated by Django 3.0.3 on 2021-10-13 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sam', '0016_auto_20211013_1318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='Assets',
        ),
    ]
